name = "bkash-nagad-payment-api"
main = "index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "payments_db"
database_id = "c14919c0-6eaf-452f-9332-741f47d011d5"
